### ISSUE TITLE
Failed to get the report

### ISSUE THREAD

**Issue by adarmanto** [thiagomarini/amazon-mws-client#2]
It happens when calling [GetReport](http://docs.developer.amazonservices.com/en_US/reports/Reports_GetReport.html) API call:

```php
$result = $mws->send('GetReport', '/Reports/2009-01-01', [
    'ReportId' => $reportId,
]);
```

> ErrorException  : simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found at /vendor/weengsapp/amazon-mws-client/src/AmazonMwsClient.php:106

The quote from official docs for the response:

> The contents of the report document. Depending on the ReportType, this will either be a tab-delimited flat file, or an XML document.

In my case was a tab-delimited flat file. Perhaps we check the result first whether is a valid XML then call `simplexml_load_string` otherwise just return the result directly?

**Comment by thiagomarini** [comment]
Change made c96d578643ba148eacf2bc899536953884f67dc0 thanks!
