### ISSUE TITLE
Tabulated response is returned as `false`

### ISSUE THREAD

**Issue by SchmalzST** [thiagomarini/amazon-mws-client#7]
The function `simplexml_load_string` returns `false` on failure, it doesn't raise an exception. Thus, tabulated response bodies lead to `AmazonMwsClient::send` returning `false` instead of the expected body. See documentation [here](https://www.php.net/manual/en/function.simplexml-load-string.php#refsect1-function.simplexml-load-string-returnvalues).

**Comment by thiagomarini** [comment]
Thanks for reporting @SchmalzST, I've released the fix https://github.com/thiagomarini/amazon-mws-client/releases/tag/2.1.0
